name: Logger Library building by Nhen

on:
  push:
    branches:
      - 'feature/*'
      - 'fixbug/*'

  pull_request:
    branches:
      - master
  workflow_dispatch:
  # Only enable build when we want to check this build stable or not
  # schedule:
  #   - cron: '0 2,8 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache clang-tidy clang-format lcov
    
    # --- Setup Docker environment ---
    - name: Prepare docker environment
      run: ./scripts/docker_prepare.sh
    
    - name: Starting docker container
      run: ./scripts/run_dev.sh CI=ON

    # --- Configure CMake with coverage enabled ---
    - name: Configure CMake
      run: ./scripts/run_dev.sh ./scripts/build_native.sh configure

    - name: Check linter
      run: ./scripts/run_dev.sh ./scripts/build_native.sh lint

    - name: Build project
      run: ./scripts/run_dev.sh ./scripts/build_native.sh build

    # --- Run all test binaries in build/test ---
    - name: Run all tests
      run: ./scripts/run_dev.sh ./scripts/build_native.sh run
    
    # --- Collect Coverage ---
    - name: Capture Coverage and Generate Report
      run: ./scripts/run_dev.sh ./scripts/get_coverage_report.sh

    # --- Upload as GitHub artifact ---
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_report/index.html
  
    - name: Cleaning build artifacts
      if: always()
      run: ./scripts/run_dev.sh rm -rf build
